// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpandemo.Models.EfModels;

public partial class Member
{
    /// <summary>
    /// 處理進度:新訂單、已取消、已送達、已退貨
    /// </summary>
    public int Id { get; set; }

    public string MemberName { get; set; }

    public string Account { get; set; }

    public string Password { get; set; }

    public string Email { get; set; }

    public bool IsConfirmed { get; set; }

    public bool IsActive { get; set; }

    public DateTime CreatedAt { get; set; }

    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}