// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace iSpandemo.Models.EfModels;

public partial class View1
{
    public int OrderId { get; set; }

    public int MemberId { get; set; }

    public string ProductName { get; set; }

    public int Qty { get; set; }

    public decimal OrigPrice { get; set; }

    public decimal UnitPrice { get; set; }
}