// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace WebApplication1.Models.EfModels;

public partial class dbFirstAppContext : DbContext
{
    public dbFirstAppContext(DbContextOptions<dbFirstAppContext> options)
        : base(options)
    {
    }

    public virtual DbSet<Faq> Faqs { get; set; }

    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder.Entity<Faq>(entity =>
        {
            entity.ToTable("FAQs");

            entity.Property(e => e.Answer)
                .IsRequired()
                .HasMaxLength(50);
            entity.Property(e => e.IsActive).HasAnnotation("Relational:DefaultConstraintName", "DF_FAQs_IsActive");
            entity.Property(e => e.Question)
                .IsRequired()
                .HasMaxLength(50);
        });

        OnModelCreatingPartial(modelBuilder);
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
}