// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace WebApplication1.Models.EfModels;

public partial class Faq
{
    public int Id { get; set; }

    public string Question { get; set; }

    public string Answer { get; set; }

    public bool IsActive { get; set; }

    public int DisplayOrder { get; set; }
}